name: Unit Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip" # caching pip dependencies

      - name: Check out Prodigy
        uses: actions/checkout@v3
        with:
          repository: explosion/prodigy
          ref: v1.14.0
          path: ./prodigy
          ssh-key: ${{ secrets.GHA_PRODIGY_READ }}

      - name: Install and setup Prodigy
        run: |
          ls -la
          pip install ./prodigy
          python -m prodigy --help
          python -m prodigy db-in fashion tests/datasets/fashion-train.jsonl
          python -m prodigy db-in fashion-eval tests/datasets/fashion-eval.jsonl

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -e .
          pip install ruff pytest
      
      - name: Run ruff
        if: always()
        shell: bash
        run: python -m ruff prodigy_hf tests

      - name: Run pytest
        if: always()
        shell: bash
        run: python -m pytest tests
